#define OV_DMI_BIOS_VENDOR ""
#define OV_DMI_BIOS_VERSION ""
#define OV_DMI_BIOS_DATE ""
#define OV_DMI_BIOS_RELEASE ""
#define OV_DMI_EC_FIRMWARE_RELEASE ""
#define OV_DMI_SYS_VENDOR ""
#define OV_DMI_PRODUCT_NAME ""
#define OV_DMI_PRODUCT_VERSION ""
#define OV_DMI_PRODUCT_SERIAL ""
#define OV_DMI_PRODUCT_UUID ""
#define OV_DMI_PRODUCT_SKU ""
#define OV_DMI_PRODUCT_FAMILY ""
#define OV_DMI_BOARD_VENDOR ""
#define OV_DMI_BOARD_NAME ""
#define OV_DMI_BOARD_VERSION ""
#define OV_DMI_BOARD_SERIAL ""
#define OV_DMI_BOARD_ASSET_TAG ""
#define OV_DMI_CHASSIS_VENDOR ""
#define OV_DMI_CHASSIS_TYPE ""
#define OV_DMI_CHASSIS_VERSION ""
#define OV_DMI_CHASSIS_SERIAL ""
#define OV_DMI_CHASSIS_ASSET_TAG ""


//These values should not be redefined
#define OV_DMI_NONE "\x00"
#define OV_DMI_STRING_MAX "\x00"
#define OV_DMI_OEM_STRING ""
